# Generated by Django 4.1.4 on 2023-01-08 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crit', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='review',
            name='time_created',
        ),
    ]
