# Generated by Django 4.1.4 on 2023-01-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crit', '0007_review_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
