# Generated by Django 4.1.4 on 2023-01-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crit', '0012_review_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='time_created',
        ),
    ]
