# Generated by Django 4.1.4 on 2023-01-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crit', '0015_remove_review_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='body2',
            field=models.TextField(blank=True, max_length=8192, verbose_name='Commentaire'),
        ),
    ]
