# Generated by Django 4.1.4 on 2023-01-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crit', '0016_review_body2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='body2',
        ),
        migrations.AddField(
            model_name='review',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
