# Generated by Django 4.1.4 on 2023-01-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_crit', '0017_remove_review_body2_review_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='time_created',
        ),
    ]
